name: easy_gitea

services:
  server:
    image: docker.io/gitea/gitea:1.23
    container_name: gitea_server
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./volumes/gitea:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_PORT_SSH:-22}:22 # SSH
      - ${GITEA_PORT_HTTP:-3000}:3000 # HTTP
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:17
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
