services:
  gitea:
    image: docker.io/gitea/gitea:1.23
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=/var/run/postgresql
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__SSH_PORT=${GITEA_PORT_SSH:-2222}
      - GITEA__server__HTTP_PORT=${GITEA_PORT_HTTP:-3000}
    volumes:
      - ./volumes/gitea/data:/data
      - ./volumes/db/sock:/var/run/postgresql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_PORT_SSH:-2222}:22 # SSH
      - ${GITEA_PORT_HTTP:-3000}:${GITEA_PORT_HTTP:-3000} # HTTP
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:17
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/sock:/var/run/postgresql
