name: compose_gitea

services:
  server:
    image: ${GITEA_IMAGE}
    container_name: gitea_server
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./volumes/gitea:/var/lib/gitea
      - ./volumes/config:/etc/gitea
      # - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_PORT_SSH:-22}:22 # SSH
      - ${GITEA_PORT_HTTP:-3000}:3000 # HTTP
    depends_on:
      - db

  db:
    image: ${POSTGRES_IMAGE}
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
